import type { CSSProperties } from "react";

const GRADIENT =
  "linear-gradient(135deg, #0d2466 0%, #1657c9 58%, #2a8fde 100%)";

export function getHeroStyle(backgroundSrc?: string): CSSProperties {
  return {
    width: "100%",
    aspectRatio: "16 / 9",
    borderRadius: 0,
    background: backgroundSrc
      ? "linear-gradient(145deg, #eef3f9 0%, #ffffff 48%, #e9eff7 100%)"
      : GRADIENT,
    boxShadow: "inset 0 0 0 1px rgba(15,23,42,.06)",
    position: "relative",
    overflow: "hidden",
    isolation: "isolate",
  };
}

export const styles = {
  wrap: {
    width: "calc(100% + 40px)",
    marginInline: -20,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  backgroundMedia: {
    position: "absolute",
    inset: 0,
    zIndex: 1,
    width: "100%",
    height: "100%",
    objectFit: "contain",
    objectPosition: "center",
    imageRendering: "auto",
  },
  bgEditButton: {
    position: "absolute",
    zIndex: 2,
    right: 10,
    bottom: 10,
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "rgba(15,23,42,0.62)",
    backdropFilter: "blur(12px) saturate(1.12)",
    border: "1px solid rgba(255,255,255,.72)",
    boxShadow: "0 10px 24px rgba(15,23,42,.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    color: "#fff",
    fontSize: 13,
  },
  bgRemoveButton: {
    position: "absolute",
    zIndex: 2,
    left: 10,
    bottom: 10,
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "rgba(15,23,42,0.62)",
    backdropFilter: "blur(12px) saturate(1.12)",
    border: "1px solid rgba(255,255,255,.72)",
    boxShadow: "0 10px 24px rgba(15,23,42,.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    color: "#fff",
    fontSize: 13,
  },
  avatarWrap: {
    position: "relative",
    zIndex: 3,
    width: 110,
    height: 110,
    marginTop: -44,
    flexShrink: 0,
  },
  avatarRing: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    overflow: "hidden",
    border: "4px solid #fff",
    boxShadow:
      "0 12px 30px rgba(15,23,42,.16), 0 0 0 1px rgba(15,23,42,.05), 0 0 0 5px var(--color-primary-soft)",
    background: "#eef0f3",
  },
  avatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  avatarFallback: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 34,
    fontWeight: 700,
    color: "#98a2b3",
  },
  avatarEditButton: {
    position: "absolute",
    right: -1,
    bottom: 1,
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#1e63d6",
    border: "2px solid #fff",
    boxShadow: "0 10px 24px rgba(30,99,214,.28)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    color: "#fff",
    fontSize: 13,
  },
  avatarRemoveButton: {
    position: "absolute",
    left: -1,
    bottom: 1,
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "rgba(15,23,42,0.68)",
    border: "2px solid #fff",
    boxShadow: "0 10px 24px rgba(15,23,42,.22)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    color: "#fff",
    fontSize: 13,
  },
} satisfies Record<string, CSSProperties>;
