import type { CSSProperties } from "react";

export const styles = {
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    background: "linear-gradient(145deg, #ffffff 0%, #f5f7fa 100%)",
    borderRadius: 16,
    minHeight: 66,
    padding: "11px 16px",
    marginBottom: 10,
    border: "1px solid rgba(15,23,42,.06)",
    textAlign: "left",
    cursor: "pointer",
    textDecoration: "none",
    boxShadow: "var(--shadow-sm)",
  },
  handle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    flexShrink: 0,
    color: "#667085",
    fontSize: 16,
    cursor: "pointer",
    background: "transparent",
    border: "none",
    borderRadius: 10,
    padding: 0,
  },
  editContent: {
    margin: 0,
    padding: "8px 16px",
    background: "transparent",
    flex: 1,
    minWidth: 0,
    width: "auto",
    overflow: "hidden",
  },
  iconBadge: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 44,
    borderRadius: 12,
    flexShrink: 0,
    fontSize: 18,
  },
  iconBadgeImage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 44,
    borderRadius: 12,
    flexShrink: 0,
    background: "#fff",
    border: "1px solid rgba(15,23,42,.06)",
    boxShadow: "var(--shadow-sm)",
  },
  iconBadgeImg: {
    width: 24,
    height: 24,
    objectFit: "contain",
  },
  body: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  label: {
    fontSize: 16,
    fontWeight: 650,
    color: "#1f2937",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  value: {
    fontSize: 14,
    color: "#7b879b",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  toggleWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    paddingLeft: 4,
  },
  arrow: {
    flexShrink: 0,
    color: "#98a2b3",
    fontSize: 12,
  },
} satisfies Record<string, CSSProperties>;
