import type { CSSProperties } from "react";
import { COLORS, SHADOWS } from "../../constants/ui";

export const styles = {
  wrap: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  hero: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    background: COLORS.surface,
    borderRadius: 20,
    overflow: "hidden",
    boxShadow: SHADOWS.sm,
    border: `1px solid ${COLORS.border}`,
  },
  heroCover: {
    position: "relative",
    width: "100%",
    height: 60,
    flexShrink: 0,
    background:
      "linear-gradient(145deg, #eef3f9 0%, #ffffff 55%, #e9eff7 100%)",
  },
  heroBody: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    padding: "0 20px 24px",
  },
  logoWrap: {
    position: "relative",
    width: 96,
    height: 96,
    marginTop: -40,
    marginBottom: 14,
  },
  logoCircle: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: COLORS.primarySoft,
    border: `4px solid ${COLORS.surface}`,
    boxShadow: SHADOWS.md,
  },
  logoImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  logoFallbackIcon: {
    fontSize: 36,
    color: COLORS.primary,
  },
  shareButton: {
    position: "absolute",
    zIndex: 2,
    right: -6,
    bottom: 2,
    width: 34,
    height: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    background: "rgba(255,255,255,.95)",
    backdropFilter: "blur(12px) saturate(1.12)",
    border: `1px solid ${COLORS.border}`,
    boxShadow: SHADOWS.sm,
    color: COLORS.text,
    fontSize: 14,
    cursor: "pointer",
  },
  name: {
    margin: 0,
    fontSize: 22,
    fontWeight: 800,
    color: COLORS.text,
    letterSpacing: "-.02em",
  },
  voenTag: {
    marginTop: 10,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    fontWeight: 700,
    color: COLORS.primaryDark,
    background: COLORS.primarySoft,
    border: "1px solid rgba(30,99,214,.14)",
    borderRadius: 999,
    padding: "6px 14px",
    fontVariantNumeric: "tabular-nums",
  },
  voenTagIcon: {
    fontSize: 11,
  },
  infoList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  infoRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    padding: "13px 16px",
    borderRadius: 16,
    background: "linear-gradient(145deg, #ffffff 0%, #f5f7fa 100%)",
    boxShadow: SHADOWS.sm,
    border: "1px solid rgba(15,23,42,.06)",
    color: COLORS.text,
    textDecoration: "none",
  },
  infoIcon: {
    width: 42,
    height: 42,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    fontSize: 17,
    background: COLORS.primarySoft,
    color: COLORS.primary,
  },
  infoText: {
    flex: 1,
    fontSize: 13.5,
    fontWeight: 650,
    lineHeight: 1.35,
    wordBreak: "break-word",
  },
  infoArrow: {
    flexShrink: 0,
    color: COLORS.textMuted,
    fontSize: 13,
  },
} satisfies Record<string, CSSProperties>;
