import type { CSSProperties } from "react";
import { COLORS, SHADOWS } from "../../constants/ui";

export const styles = {
  title: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 17,
    fontWeight: 500,
    color: COLORS.text,
  },
  titleIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 10,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: COLORS.primaryTint,
    color: COLORS.primary,
    flexShrink: 0,
  },
  titleIcon: {
    fontSize: 17,
  },
  previewButton: {
    width: 38,
    height: 38,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: `1px solid ${COLORS.borderSubtle}`,
    borderRadius: 10,
    color: COLORS.primary,
    fontSize: 17,
  },
  card: {
    marginBottom: 16,
    borderRadius: 14,
    border: "none",
    boxShadow: SHADOWS.card,
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  uploadButton: {
    borderRadius: 14,
    height: 46,
    padding: "0 18px",
    fontSize: 15,
    fontWeight: 600,
    borderColor: COLORS.borderSubtle,
    color: COLORS.text,
  },
  voenBadge: {
    display: "inline-flex",
    alignSelf: "flex-start",
    padding: "7px 12px",
    border: `1px solid ${COLORS.borderSubtle}`,
    borderRadius: 10,
    background: COLORS.surfaceSubtle,
    fontSize: 14,
    fontWeight: 600,
    color: COLORS.labelMuted,
    whiteSpace: "nowrap",
  },
  voenValue: {
    color: COLORS.primary,
  },
  divider: {
    height: 1,
    background: COLORS.avatarMuted,
    border: "none",
    margin: "0 0 16px",
  },
  saveButton: {
    width: "100%",
    height: 44,
    borderRadius: 14,
    fontSize: 15,
    fontWeight: 600,
  },
} satisfies Record<string, CSSProperties>;
