import type { CSSProperties } from "react";
import { COLORS, SHADOWS } from "../../constants/ui";

export const styles = {
  header: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "6px 4px 18px",
    borderBottom: `1px solid ${COLORS.border}`,
    marginBottom: 16,
  },
  headerLogo: {
    width: 56,
    height: 56,
    flexShrink: 0,
    borderRadius: "50%",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: COLORS.primarySoft,
    border: `1px solid ${COLORS.border}`,
  },
  headerLogoImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    padding: 5,
  },
  headerLogoFallback: {
    fontSize: 22,
    color: COLORS.primary,
  },
  headerText: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
  },
  headerName: {
    fontSize: 16,
    fontWeight: 700,
    color: COLORS.text,
  },
  headerVoen: {
    fontSize: 12,
    fontWeight: 600,
    color: COLORS.textSecondary,
  },
  headerVoenValue: {
    color: COLORS.primary,
    fontWeight: 700,
  },
  qrSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: "16px 0 20px",
    marginBottom: 4,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  qrImage: {
    width: 156,
    height: 156,
    borderRadius: 16,
    border: `1px solid ${COLORS.border}`,
    padding: 8,
    background: COLORS.surface,
  },
  qrFallback: {
    width: 156,
    height: 156,
    borderRadius: 16,
    border: `1px dashed ${COLORS.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: COLORS.textMuted,
    fontWeight: 700,
  },
  qrHint: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  infoList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginBottom: 20,
  },
  infoRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 14,
    background: COLORS.surfaceMuted,
    border: `1px solid ${COLORS.border}`,
  },
  infoRowLink: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 14,
    background: COLORS.surfaceMuted,
    border: `1px solid ${COLORS.border}`,
    textDecoration: "none",
    cursor: "pointer",
  },
  infoIcon: {
    width: 36,
    height: 36,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    background: COLORS.surface,
    color: COLORS.primary,
    fontSize: 15,
    boxShadow: SHADOWS.sm,
  },
  infoBody: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: COLORS.textMuted,
    textTransform: "uppercase",
    letterSpacing: ".03em",
  },
  infoValue: {
    fontSize: 13.5,
    fontWeight: 600,
    color: COLORS.text,
    wordBreak: "break-word",
  },
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  formatSelector: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    padding: 3,
    background: COLORS.surfaceMuted,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 999,
  },
  formatButton: {
    minHeight: 36,
    border: "none",
    borderRadius: 999,
    background: "transparent",
    color: COLORS.textSecondary,
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    transition:
      "background 180ms cubic-bezier(.4,0,.2,1), color 180ms ease, box-shadow 180ms ease",
  },
  formatButtonSelected: {
    background: COLORS.primary,
    color: "#fff",
    boxShadow: "0 8px 18px rgba(27, 74, 117, 0.22)",
  },
  shareRow: {
    display: "flex",
    justifyContent: "center",
    gap: 22,
    marginTop: 6,
  },
  shareIcon: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    padding: 0,
    margin: 0,
    border: "none",
    outline: "none",
    appearance: "none",
    background: "transparent",
    color: COLORS.textSecondary,
    font: "inherit",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
    textDecoration: "none",
  },
  shareIconCircle: {
    width: 52,
    height: 52,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    color: "#fff",
    border: "none",
    boxShadow: SHADOWS.sm,
  },
  shareIconCircleWhatsapp: {
    background: "linear-gradient(145deg, #2fd66b 0%, #22b95a 100%)",
  },
  shareIconCircleEmail: {
    background: `linear-gradient(145deg, ${COLORS.primary} 0%, #123a5c 100%)`,
  },
  shareIconCircleNative: {
    background: "linear-gradient(145deg, #1f2a44 0%, #16224f 100%)",
  },
  shareIconGlyph: {
    fontSize: 21,
  },
} satisfies Record<string, CSSProperties>;
