import type { CSSProperties } from "react";

export const styles = {
  card: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 10px",
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #eef0f3",
    marginBottom: 10,
  },
  dotsButton: {
    width: 32,
    height: 32,
    flexShrink: 0,
    border: "none",
    background: "transparent",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#667085",
    fontSize: 18,
    cursor: "pointer",
  },
  avatarButton: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
  },
  info: {
    flex: 1,
    minWidth: 0,
    cursor: "pointer",
  },
  statusToggle: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  statusToggleLabel: {
    fontSize: 10.5,
    fontWeight: 500,
  },
  nameRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  name: {
    fontWeight: 600,
    fontSize: 14.5,
    color: "#1f2937",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  adminTag: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "#1e63d6",
    background: "#eaf1ff",
    borderRadius: 6,
    padding: "1px 6px",
    flexShrink: 0,
  },
  jobTitle: {
    fontSize: 12.5,
    color: "#8c98ac",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  sheetActions: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 10,
  },
  sheetAction: {
    width: "100%",
    minWidth: 0,
    minHeight: 62,
    display: "grid",
    gridTemplateColumns: "22px minmax(0, 1fr)",
    alignItems: "center",
    gap: 10,
    border: "1px solid #e5eaf1",
    background: "#f8fafc",
    borderRadius: 12,
    padding: "11px 13px",
    fontSize: 14,
    fontWeight: 650,
    color: "#1f2937",
    textAlign: "left",
    cursor: "pointer",
  },
  sheetActionIcon: {
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 17,
    flexShrink: 0,
  },
  sheetActionLabel: {
    minWidth: 0,
    lineHeight: 1.25,
  },
  sheetActionDanger: {
    background: "#fff7f7",
    borderColor: "#ffd3d3",
    color: "#dc2626",
  },
} satisfies Record<string, CSSProperties>;
