import type { CSSProperties } from "react";
import { COLORS, SHADOWS } from "../../constants/ui";

export const styles = {
  toolbarCard: {
    marginBottom: 16,
    borderRadius: 12,
    borderColor: "#e3ebf7",
    boxShadow: SHADOWS.sm,
  },
  toolbarBody: {
    padding: 16,
  },
  filterBlock: {
    display: "grid",
    gap: 6,
  },
  filterLabel: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: 700,
  },
  statTile: {
    minHeight: 58,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 12,
    background: "#f7fbff",
    border: "1px solid #dce8fc",
  },
  statIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: COLORS.primary,
    background: "#eaf2fe",
    flexShrink: 0,
  },
  statLabel: {
    display: "block",
    color: COLORS.textSecondary,
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1.15,
  },
  statValue: {
    display: "block",
    color: COLORS.ink,
    fontSize: 18,
    fontWeight: 900,
    lineHeight: 1.1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 220,
  },
  tableCard: {
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: SHADOWS.md,
  },
  tableBody: {
    padding: 0,
  },
  employeeCell: {
    display: "grid",
    gridTemplateColumns: "minmax(170px, auto) 1fr",
    alignItems: "center",
    columnGap: 12,
    minWidth: 0,
    width: "100%",
    maxWidth: "100%",
    paddingLeft: 24,
    paddingRight: 24,
  },
  employeeAvatarButton: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "zoom-in",
    lineHeight: 0,
    flexShrink: 0,
  },
  employeeText: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
  },
  employeeName: {
    display: "block",
    color: COLORS.text,
    fontSize: 14,
    fontWeight: 400,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: "100%",
  },
  employeeHint: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: COLORS.text,
    fontSize: 15,
    fontWeight: 500,
    flexShrink: 0,
  },
  clickableRow: {
    cursor: "pointer",
  },
  paginationWrap: {
    display: "flex",
    justifyContent: "center",
    paddingTop: 16,
  },
} satisfies Record<string, CSSProperties>;
