import type { CSSProperties } from "react";
import { COLORS, SHADOWS } from "../../constants/ui";

export const styles = {
  toolbarCard: {
    marginBottom: 14,
    borderRadius: 14,
    border: "none",
    boxShadow: SHADOWS.card,
  },
  toolbarBody: {
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  filterGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  filterTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  filterIconBadge: {
    width: 30,
    height: 30,
    borderRadius: 10,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: COLORS.surfaceMuted,
    color: COLORS.labelMuted,
    flexShrink: 0,
  },
  filterLabel: {
    color: COLORS.labelMuted,
    fontSize: 14,
    fontWeight: 600,
  },
  filterField: {
    width: "100%",
  },
  statCard: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: 14,
    borderRadius: 14,
    background: COLORS.surfaceSubtle,
    marginBottom: 14,
  },
  statIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: COLORS.primary,
    background: COLORS.primaryTint,
    fontSize: 20,
    flexShrink: 0,
  },
  statLabel: {
    display: "block",
    color: COLORS.textSubtle,
    fontSize: 12,
    fontWeight: 400,
    lineHeight: 1.3,
  },
  statValue: {
    display: "block",
    color: COLORS.text,
    fontSize: 22,
    fontWeight: 700,
    lineHeight: 1.2,
    marginTop: 2,
  },
  tableCard: {
    borderRadius: 14,
    overflow: "hidden",
    border: "none",
    boxShadow: SHADOWS.card,
  },
  tableBody: {
    padding: 0,
  },
  logRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "12px 16px",
    borderBottom: "1px solid rgba(15,23,42,0.05)",
    cursor: "pointer",
    width: "100%",
    background: "transparent",
    border: "none",
    textAlign: "left",
  },
  logRowLast: {
    borderBottom: "none",
  },
  logEmployee: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  logAvatarButton: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "zoom-in",
    lineHeight: 0,
    flexShrink: 0,
  },
  logAvatar: {
    background: COLORS.avatarMuted,
    color: COLORS.textSubtle,
    fontWeight: 600,
    fontSize: 14,
  },
  logName: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  logDate: {
    color: COLORS.textSubtle,
    fontSize: 14,
    fontWeight: 400,
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
} satisfies Record<string, CSSProperties>;
