import type { CSSProperties } from "react";

export const styles = {
  qrView: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
  },
  headerIcon: {
    width: 40,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    background: "var(--color-primary-soft)",
    fontSize: 20,
    color: "var(--color-primary)",
    marginBottom: 8,
  },
  title: {
    fontFamily: "var(--font-display)",
    fontSize: 18,
    lineHeight: 1.2,
    fontWeight: 750,
    color: "#0f172a",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "#667085",
    maxWidth: 260,
    marginBottom: 12,
  },
  qrFrame: {
    padding: 10,
    background: "#fff",
    border: "1px solid rgba(15,23,42,.07)",
    borderRadius: 16,
    marginBottom: 12,
    boxShadow: "0 10px 26px rgba(15,23,42,.07)",
  },
  actions: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  formatSelector: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    padding: 2,
    background: "#f3f5f8",
    border: "1px solid #e4e8ef",
    borderRadius: 12,
  },
  formatButton: {
    minHeight: 40,
    border: "none",
    borderRadius: 10,
    background: "transparent",
    color: "#344054",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    transition:
      "background 180ms cubic-bezier(.4,0,.2,1), color 180ms ease, box-shadow 180ms ease, transform 180ms cubic-bezier(.22,1,.36,1)",
  },
  formatButtonSelected: {
    background: "#1e63d6",
    color: "#fff",
    boxShadow: "0 8px 18px rgba(30, 99, 214, 0.22)",
  },
  downloadButton: {
    borderColor: "#1e63d6",
    color: "#1e63d6",
    fontWeight: 700,
    minHeight: 44,
    height: 44,
    borderRadius: 12,
    fontSize: 14,
  },
  primaryButton: {
    minHeight: 44,
    height: 44,
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 700,
  },
  shareView: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  backButton: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    border: "none",
    background: "transparent",
    color: "#667085",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
  },
  employeeName: {
    fontFamily: "var(--font-display)",
    fontSize: 18,
    fontWeight: 750,
    color: "#0f172a",
    textAlign: "center",
  },
  linkRow: {
    display: "flex",
    gap: 8,
  },
  linkInput: {
    flex: 1,
    background: "#f7f8fa",
  },
  shareRow: {
    display: "flex",
    justifyContent: "center",
    gap: 22,
    marginTop: 4,
  },
  shareIcon: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    border: "none",
    background: "transparent",
    color: "#344054",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
    textDecoration: "none",
  },
  shareIconCircle: {
    width: 56,
    height: 56,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    background: "linear-gradient(145deg, #fff 0%, #edf3fb 100%)",
    color: "#1e63d6",
    border: "1px solid rgba(15,23,42,.06)",
    boxShadow: "var(--shadow-sm)",
  },
  shareIconGlyph: {
    fontSize: 22,
  },
} satisfies Record<string, CSSProperties>;
