import type { ReactNode } from "react";
import { buildWhatsAppLink } from "../utils/url";
import {
  EnvironmentOutlined,
  FacebookOutlined,
  GithubOutlined,
  GlobalOutlined,
  IdcardOutlined,
  InstagramOutlined,
  LinkedinOutlined,
  MailOutlined,
  MessageOutlined,
  MobileOutlined,
  PhoneOutlined,
  PlaySquareOutlined,
  SendOutlined,
  SoundOutlined,
  TeamOutlined,
  TwitterOutlined,
  VideoCameraOutlined,
  WhatsAppOutlined,
  YoutubeOutlined,
} from "@ant-design/icons";
import type {
  CoreLinkKey,
  LinkCategory,
  LinkFieldKind,
  LinkType,
  LinkTypeMeta,
} from "../types";

export const FEATURED_TYPES: LinkType[] = ["contact-card", "website"];

export const LINK_CATEGORY_LABELS: Record<LinkCategory, string> = {
  contact: "Kontaktlar",
  social: "Sosial media",
  finance: "Maliyyə",
  music: "Musiqi",
  business: "Biznes",
  other: "Digər",
};

export const LINK_CATEGORY_ORDER: LinkCategory[] = [
  "contact",
  "social",
  "finance",
  "music",
  "business",
];

const ICONS = "/imgs/icons";

export const LINK_TYPE_META: Record<LinkType, LinkTypeMeta> = {
  "contact-card": {
    title: "Kontakt kartı",
    placeholder: "Haqqınızda qısa məlumat",
    icon: <IdcardOutlined />,
    iconSrc: `${ICONS}/contacts.svg`,
    category: "contact",
    fieldKind: "url",
  },
  phone: {
    title: "Telefon",
    placeholder: "+9941234567890",
    icon: <PhoneOutlined />,
    iconSrc: `${ICONS}/phone.svg`,
    category: "contact",
    fieldKind: "phone",
  },
  email: {
    title: "Email",
    placeholder: "ad@nümunə.com",
    icon: <MailOutlined />,
    iconSrc: `${ICONS}/mail.svg`,
    category: "contact",
    fieldKind: "email",
  },
  messenger: {
    title: "Messenger",
    placeholder: "https://m.me/istifadeci",
    icon: <MessageOutlined />,
    iconSrc: `${ICONS}/messenger.svg`,
    category: "contact",
    fieldKind: "url",
  },
  whatsapp: {
    title: "WhatsApp",
    placeholder: "+9941234567890",
    icon: <WhatsAppOutlined />,
    iconSrc: `${ICONS}/whatsapp.svg`,
    category: "contact",
    fieldKind: "phone",
  },
  "whatsapp-business": {
    title: "WhatsApp Business",
    placeholder: "+9941234567890",
    icon: <WhatsAppOutlined />,
    iconSrc: `${ICONS}/whatsapp-business.svg`,
    category: "contact",
    fieldKind: "phone",
  },
  sms: {
    title: "SMS",
    placeholder: "+9941234567890",
    icon: <MessageOutlined />,
    iconSrc: `${ICONS}/sms.svg`,
    category: "contact",
    fieldKind: "phone",
  },
  telegram: {
    title: "Telegram",
    placeholder: "https://t.me/istifadeci",
    icon: <SendOutlined />,
    iconSrc: `${ICONS}/telegram.svg`,
    category: "social",
    fieldKind: "url",
  },
  viber: {
    title: "Viber",
    placeholder: "+9941234567890",
    icon: <PhoneOutlined />,
    iconSrc: `${ICONS}/viber.svg`,
    category: "contact",
    fieldKind: "phone",
  },
  zoom: {
    title: "Zoom",
    placeholder: "https://zoom.us/j/...",
    icon: <VideoCameraOutlined />,
    iconSrc: `${ICONS}/zoom.svg`,
    category: "contact",
    fieldKind: "url",
  },
  skype: {
    title: "Skype",
    placeholder: "https://join.skype.com/...",
    icon: <VideoCameraOutlined />,
    iconSrc: `${ICONS}/skype.svg`,
    category: "contact",
    fieldKind: "url",
  },
  facebook: {
    title: "Facebook",
    placeholder: "https://facebook.com/...",
    icon: <FacebookOutlined />,
    iconSrc: `${ICONS}/facebook.svg`,
    category: "social",
    fieldKind: "url",
  },
  instagram: {
    title: "Instagram",
    placeholder: "istifadeci_adi",
    icon: <InstagramOutlined />,
    iconSrc: `${ICONS}/instagram.svg`,
    category: "social",
    fieldKind: "username",
    urlPrefix: "https://www.instagram.com/",
  },
  linkedin: {
    title: "LinkedIn",
    placeholder: "https://linkedin.com/in/...",
    icon: <LinkedinOutlined />,
    iconSrc: `${ICONS}/linkedin.svg`,
    category: "social",
    fieldKind: "url",
  },
  tiktok: {
    title: "TikTok",
    placeholder: "istifadeci_adi",
    icon: <PlaySquareOutlined />,
    iconSrc: `${ICONS}/tiktok.svg`,
    category: "social",
    fieldKind: "username",
    urlPrefix: "https://www.tiktok.com/@",
  },
  youtube: {
    title: "YouTube",
    placeholder: "https://youtube.com/...",
    icon: <YoutubeOutlined />,
    iconSrc: `${ICONS}/youtube.svg`,
    category: "social",
    fieldKind: "url",
  },
  snapchat: {
    title: "Snapchat",
    placeholder: "https://snapchat.com/add/...",
    icon: <MessageOutlined />,
    iconSrc: `${ICONS}/snapchat.svg`,
    category: "social",
    fieldKind: "url",
  },
  threads: {
    title: "Threads",
    placeholder: "https://threads.net/@...",
    icon: <MessageOutlined />,
    iconSrc: `${ICONS}/threads.svg`,
    category: "social",
    fieldKind: "url",
  },
  twitch: {
    title: "Twitch",
    placeholder: "https://twitch.tv/...",
    icon: <PlaySquareOutlined />,
    iconSrc: `${ICONS}/twitch-tv.svg`,
    category: "social",
    fieldKind: "url",
  },
  vk: {
    title: "VK",
    placeholder: "https://vk.com/...",
    icon: <TeamOutlined />,
    iconSrc: `${ICONS}/vk.svg`,
    category: "social",
    fieldKind: "url",
  },
  wechat: {
    title: "WeChat",
    placeholder: "https://wechat.com/...",
    icon: <MessageOutlined />,
    iconSrc: `${ICONS}/wechat.svg`,
    category: "social",
    fieldKind: "url",
  },
  x: {
    title: "X (Twitter)",
    placeholder: "https://x.com/...",
    icon: <TwitterOutlined />,
    iconSrc: `${ICONS}/twitter_new.svg`,
    category: "social",
    fieldKind: "url",
  },
  github: {
    title: "GitHub",
    placeholder: "https://github.com/...",
    icon: <GithubOutlined />,
    iconSrc: `${ICONS}/github.svg`,
    category: "social",
    fieldKind: "url",
  },
  discord: {
    title: "Discord",
    placeholder: "https://discord.gg/...",
    icon: <TeamOutlined />,
    iconSrc: `${ICONS}/discord.svg`,
    category: "social",
    fieldKind: "url",
  },
  slack: {
    title: "Slack",
    placeholder: "https://workspace.slack.com/...",
    icon: <MessageOutlined />,
    iconSrc: `${ICONS}/slack.svg`,
    category: "social",
    fieldKind: "url",
  },
  spotify: {
    title: "Spotify",
    placeholder: "https://open.spotify.com/...",
    icon: <SoundOutlined />,
    iconSrc: `${ICONS}/spotify.svg`,
    category: "music",
    fieldKind: "url",
  },
  applemusic: {
    title: "Apple Music",
    placeholder: "https://music.apple.com/...",
    icon: <SoundOutlined />,
    iconSrc: `${ICONS}/applemusic.svg`,
    category: "music",
    fieldKind: "url",
  },
  "youtube-music": {
    title: "YouTube Music",
    placeholder: "https://music.youtube.com/...",
    icon: <SoundOutlined />,
    iconSrc: `${ICONS}/youtube_music.svg`,
    category: "music",
    fieldKind: "url",
  },
  googlemaps: {
    title: "Xəritələr",
    placeholder: "https://maps.google.com/...",
    icon: <EnvironmentOutlined />,
    iconSrc: `${ICONS}/maps.svg`,
    category: "business",
    fieldKind: "url",
  },
  amazon: {
    title: "Amazon",
    placeholder: "https://amazon.com/...",
    icon: <GlobalOutlined />,
    iconSrc: `${ICONS}/amazon.svg`,
    category: "business",
    fieldKind: "url",
  },
  lalafo: {
    title: "Lalafo",
    placeholder: "https://lalafo.az/...",
    icon: <GlobalOutlined />,
    iconSrc: `${ICONS}/lalafoaz.svg`,
    category: "business",
    fieldKind: "url",
  },
  tapaz: {
    title: "Tap.az",
    placeholder: "https://tap.az/...",
    icon: <GlobalOutlined />,
    iconSrc: `${ICONS}/tapaz.svg`,
    category: "business",
    fieldKind: "url",
  },
  website: {
    title: "Sayt linki",
    placeholder: "https://example.com",
    icon: <GlobalOutlined />,
    category: "other",
    fieldKind: "url",
  },
};

interface CoreLinkMeta {
  label: string;
  icon: ReactNode;
  iconSrc?: string;
  fieldKind: Exclude<LinkFieldKind, "email">;
  placeholder: string;
  urlPrefix?: string;
  buildHref: (value: string) => string;
}

export const CORE_LINK_META: Record<CoreLinkKey, CoreLinkMeta> = {
  phone1: {
    label: "Telefon",
    icon: <PhoneOutlined />,
    iconSrc: `${ICONS}/phone.svg`,
    fieldKind: "phone",
    placeholder: "+9941234567890",
    buildHref: (v) => `tel:${v}`,
  },
  phone2: {
    label: "Şəxsi telefon",
    icon: <MobileOutlined />,
    iconSrc: `${ICONS}/phone.svg`,
    fieldKind: "phone",
    placeholder: "+9941234567890",
    buildHref: (v) => `tel:${v}`,
  },
  whatsappPhone: {
    label: "WhatsApp",
    icon: <WhatsAppOutlined />,
    iconSrc: `${ICONS}/whatsapp.svg`,
    fieldKind: "phone",
    placeholder: "+9941234567890",
    buildHref: buildWhatsAppLink,
  },
  linkedinUrl: {
    label: "LinkedIn",
    icon: <LinkedinOutlined />,
    iconSrc: `${ICONS}/linkedin.svg`,
    fieldKind: "url",
    placeholder: "https://...",
    buildHref: (v) => v,
  },
  facebookUrl: {
    label: "Facebook",
    icon: <FacebookOutlined />,
    iconSrc: `${ICONS}/facebook.svg`,
    fieldKind: "url",
    placeholder: "https://...",
    buildHref: (v) => v,
  },
  instagramUrl: {
    label: "Instagram",
    icon: <InstagramOutlined />,
    iconSrc: `${ICONS}/instagram.svg`,
    fieldKind: "username",
    placeholder: "istifadeci_adi",
    urlPrefix: "https://www.instagram.com/",
    buildHref: (v) => v,
  },
  googleMapsUrl: {
    label: "Google Maps",
    icon: <EnvironmentOutlined />,
    iconSrc: `${ICONS}/maps.svg`,
    fieldKind: "url",
    placeholder: "https://...",
    buildHref: (v) => v,
  },
};

export const CORE_LINK_ORDER: CoreLinkKey[] = [
  "phone1",
  "phone2",
  "whatsappPhone",
  "linkedinUrl",
  "facebookUrl",
  "instagramUrl",
  "googleMapsUrl",
];

export const CORE_LINK_CATEGORY: Record<CoreLinkKey, LinkCategory> = {
  phone1: "contact",
  phone2: "contact",
  whatsappPhone: "contact",
  linkedinUrl: "social",
  facebookUrl: "social",
  instagramUrl: "social",
  googleMapsUrl: "business",
};

export const FALLBACK_LINK_META: LinkTypeMeta = {
  title: "Keçid",
  placeholder: "https://...",
  icon: <GlobalOutlined />,
  category: "other",
  fieldKind: "url",
};
