export const strings = {
  common: {
    save: "Saxla",
    cancel: "Ləğv et",
    yes: "Bəli",
    no: "Xeyr",
    activate: "Aktivləşdir",
    deactivate: "Deaktivləşdir",
    total: "Cəmi",
    noData: "Məlumat yoxdur",
    tryAgain: "Yenidən cəhd et",
  },
  auth: {
    logout: "Çıxış",
    email: "E-poçt",
    password: "Şifrə",
    loginError: "Məlumatlar düzgün daxil edilməyib.",
    emailRequired: "E-poçt tələb olunur",
    passwordRequired: "Şifrə tələb olunur",
    emailInvalid: "E-poçt ünvanı düzgün deyil",
    sessionExpired: "Sessiya müddəti bitmişdir. Yenidən daxil olun.",
    superAdminRole: "Super Admin",
    companyAdminRole: "Şirkət admini",
    employeeRole: "Əməkdaş",
  },
  navigation: {
    dashboard: "İdarə Paneli",
    companies: "Şirkətlər",
    importExport: "İdxal və İxrac",
    auditLogs: "Audit Jurnalı",
    profile: "Profilim",
    settings: "Tənzimləmələr",
    statistics: "Statistika",
    scanLogs: "Skan loqları",
    team: "Əməkdaşlar",
  },
  employees: {
    createButton: "Yeni Əməkdaş",
    form: {
      createTitle: "Yeni Əməkdaş Yarat",
      position: "Vəzifə",
      cancelButton: "Ləğv et",
    },
    actions: {
      edit: "Redaktə et",
      viewCard: "Vizitkarta Bax",
    },
    confirmDeactivate:
      "Bu əməkdaşı deaktivləşdirmək istəyirsiniz? Əməkdaş arxivə keçəcək.",
    confirmActivate: "Bu əməkdaşı aktivləşdirmək istəyirsiniz?",
    tabs: {
      active: "Aktiv",
      archive: "Arxiv",
    },
    archivedHint:
      "Deaktiv edilmiş əməkdaşlar arxivdə saxlanılır — tarixçə və analitika itmir.",
    identifiers: "İdentifikatorlar",
    uidLabel: "QR-UID (unikal kod)",
    cardLinkLabel: "Vizitkart linki",
    nfcLabel: "NFC etiket (URL)",
    createSuccess: "Əməkdaş uğurla yaradıldı",
    updateSuccess: "Əməkdaş uğurla yeniləndi",
    statusUpdateSuccess: "Status uğurla yeniləndi",
    empty: "Hələ heç bir əməkdaş yoxdur",
  },
  companies: {
    title: "Şirkətlər",
    createButton: "Yeni Şirkət",
    form: {
      createTitle: "Yeni Şirkət Yarat",
      name: "Şirkət Adı",
      namePlaceholder: "Şirkətin adını daxil edin",
      voen: "VÖEN",
      voenPlaceholder: "Vergi ödəyicisinin eyniləşdirmə nömrəsi",
      logo: "Şirkət Logosu",
      logoHint: "PNG, JPG, WebP — maks. 2MB",
      address: "Ünvan",
      addressPlaceholder: "Şirkətin ünvanını daxil edin",
      employeeLimit: "Əməkdaş Limiti",
    },
    createSuccess: "Şirkət uğurla yaradıldı",
    updateSuccess: "Şirkət uğurla yeniləndi",
    statusUpdateSuccess: "Şirkət statusu yeniləndi",
    empty: "Hələ heç bir şirkət yoxdur",
  },
  publicCard: {
    inactive: "Vizitkart qeyri-aktivdir",
    notFound: "Vizitkart tapılmadı",
    notFoundSubtext: "Bu UID ilə vizitkart mövcud deyil.",
  },
  importExport: {
    title: "İxrac",
    exportSection: "Excel İxrac (.xlsx)",
    exportSuccess: "İxrac uğurla tamamlandı",
    exportHint:
      "Bütün əməkdaşların məlumatları (S.A.A., vəzifə, əlaqə, vizitkart linki) .xlsx faylına yazılır.",
  },
  auditLogs: {
    title: "Audit Jurnalı",
    empty: "Audit qeydi tapılmadı",
  },
  settings: {
    title: "Tənzimləmələr",
  },
  errors: {
    generic: "Xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.",
    notFound: "Məlumat tapılmadı",
    unauthorized: "Giriş etməlisiniz",
    forbidden: "Bu səhifəyə giriş icazəniz yoxdur",
    serverError: "Server xətası. Zəhmət olmasa yenidən cəhd edin.",
    networkError: "Şəbəkə xətası. İnternet bağlantınızı yoxlayın.",
    conflict:
      "Bu məlumat artıq dəyişdirilib. Səhifəni yeniləyib yenidən cəhd edin.",
  },
} as const;
