import type { CSSProperties } from "react";
import { COLORS } from "../../constants/ui";

export const styles = {
  page: {
    height: "100dvh",
    overflow: "hidden",
    background: COLORS.primaryTint,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "clamp(8px, 3dvh, 20px) 20px",
  },
  wrap: {
    width: "100%",
    maxWidth: 390,
  },
  brandCard: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    background: "#fff",
    borderRadius: 20,
    boxShadow: "0 1px 2px rgba(26,26,26,0.04), 0 8px 24px rgba(27,74,117,0.1)",
    padding: "clamp(10px, 2.2dvh, 20px)",
    marginBottom: "clamp(8px, 1.8dvh, 16px)",
  },
  logoBox: {
    width: "clamp(40px, 7dvh, 56px)",
    height: "clamp(40px, 7dvh, 56px)",
    flexShrink: 0,
    borderRadius: 14,
    background: "#f7f9fc",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 6,
  },
  logoImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  brandName: {
    fontSize: 20,
    fontWeight: 600,
    color: COLORS.primary,
  },
  brandSubtitle: {
    fontSize: 12,
    color: COLORS.textSubtle,
    marginTop: 0,
  },
  formCard: {
    background: "#fff",
    borderRadius: 20,
    boxShadow: "0 1px 2px rgba(26,26,26,0.04), 0 8px 24px rgba(26,26,26,0.06)",
    padding: "clamp(12px, 2.2dvh, 20px)",
    marginBottom: "clamp(8px, 1.8dvh, 16px)",
  },
  formTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: "#1a1a1a",
    margin: 0,
  },
  formSubtitle: {
    fontSize: 13,
    color: COLORS.textSubtle,
    margin: "4px 0 clamp(8px, 1.8dvh, 16px)",
  },
  alert: {
    marginBottom: "clamp(8px, 1.8dvh, 16px)",
  },
  fieldGroup: {
    marginBottom: "clamp(8px, 1.8dvh, 16px)",
  },
  fieldLabel: {
    display: "block",
    fontSize: 14,
    fontWeight: 500,
    color: "#1a1a1a",
    marginBottom: "clamp(4px, 1dvh, 8px)",
  },
  inputWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    height: "clamp(38px, 5.5dvh, 44px)",
    padding: "0 12px",
    border: "1px solid #e3e6e4",
    borderRadius: 12,
  },
  inputWrapError: {
    borderColor: COLORS.danger,
  },
  inputIcon: {
    fontSize: 16,
    color: COLORS.textSubtle,
    flexShrink: 0,
  },
  input: {
    flex: 1,
    minWidth: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: 14,
    fontFamily: "inherit",
    color: "#1a1a1a",
  },
  eyeToggle: {
    flexShrink: 0,
    width: 32,
    height: 32,
    border: "none",
    background: "transparent",
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    color: COLORS.textSubtle,
    cursor: "pointer",
  },
  errorText: {
    fontSize: 12,
    color: COLORS.danger,
    marginTop: 6,
  },
  submitButton: {
    width: "100%",
    height: "clamp(42px, 6dvh, 52px)",
    borderRadius: 12,
    background: COLORS.primary,
    border: "none",
    color: "#fff",
    fontSize: 14,
    fontWeight: 500,
    marginTop: 4,
  },
  superAdminCard: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    background: "#fff",
    borderRadius: 20,
    boxShadow: "0 1px 2px rgba(26,26,26,0.04), 0 8px 24px rgba(26,26,26,0.06)",
    padding: "clamp(10px, 1.8dvh, 16px)",
    marginBottom: "clamp(8px, 1.8dvh, 16px)",
    textDecoration: "none",
    cursor: "pointer",
  },
  superAdminIcon: {
    width: "clamp(36px, 6dvh, 44px)",
    height: "clamp(36px, 6dvh, 44px)",
    flexShrink: 0,
    borderRadius: 12,
    background: COLORS.primaryTint,
    color: COLORS.primary,
    fontSize: 18,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  superAdminText: {
    flex: 1,
    minWidth: 0,
  },
  superAdminTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: COLORS.primary,
  },
  superAdminSubtitle: {
    fontSize: 12,
    color: COLORS.textSubtle,
    marginTop: 2,
  },
  superAdminChevron: {
    flexShrink: 0,
    color: COLORS.textSubtle,
    fontSize: 14,
  },
  footer: {
    margin: "clamp(8px, 2.4dvh, 24px) 0 0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    fontSize: 12,
    lineHeight: "18px",
    color: COLORS.textSubtle,
  },
  footerLogoLink: {
    display: "flex",
    alignItems: "center",
  },
} satisfies Record<string, CSSProperties>;
