import type { CSSProperties } from "react";
import { COLORS, SHADOWS } from "../../constants/ui";

export function getCoverStyle(image?: string): CSSProperties {
  return {
    ...styles.cover,
    background: image
      ? "linear-gradient(145deg, #eef3f9 0%, #ffffff 48%, #e9eff7 100%)"
      : "linear-gradient(145deg, var(--card-accent-deep, #0d2466) 0%, var(--card-accent, #1657c9) 58%, #2a8fde 100%)",
  };
}

export function getIconTileStyle(color: string): CSSProperties {
  return {
    ...styles.iconTile,
    color,
  };
}

export const styles = {
  card: {
    background: "#fff",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    color: "var(--color-text)",
  },
  cover: {
    position: "relative",
    width: "100%",
    aspectRatio: "16 / 9",
    margin: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 0,
    boxShadow: "inset 0 0 0 1px rgba(15,23,42,.06)",
    isolation: "isolate",
  },
  coverMedia: {
    position: "absolute",
    inset: 0,
    zIndex: 1,
    width: "100%",
    height: "100%",
    objectFit: "contain",
    objectPosition: "center",
    imageRendering: "auto",
  },
  coverPattern: {
    position: "absolute",
    inset: 0,
    opacity: 0.18,
    backgroundImage:
      "radial-gradient(rgba(255,255,255,.8) 1px, transparent 1px)",
    backgroundSize: "18px 18px",
  },
  profileSection: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0 18px",
    textAlign: "center",
  },
  avatarWrap: {
    position: "relative",
    zIndex: 2,
    width: 110,
    height: 110,
    marginTop: -44,
  },
  avatarCircle: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    overflow: "hidden",
    border: "4px solid #fff",
    background: "#e9eef8",
    boxShadow:
      "0 12px 30px rgba(15,23,42,.16), 0 0 0 1px rgba(30,99,214,.10), 0 0 0 5px var(--color-primary-soft), 0 0 0 7px rgba(42,210,230,.08)",
  },
  shareButton: {
    position: "absolute",
    zIndex: 3,
    right: -10,
    bottom: 2,
    width: 34,
    height: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    background: "rgba(255,255,255,.92)",
    backdropFilter: "blur(12px) saturate(1.12)",
    border: "1px solid rgba(15,23,42,.1)",
    boxShadow: "0 10px 24px rgba(15,23,42,.13)",
    color: COLORS.text,
    fontSize: 14,
    cursor: "pointer",
  },
  coverEditButton: {
    position: "absolute",
    zIndex: 3,
    right: 14,
    top: 10,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 30,
    padding: "6px 11px 6px 10px",
    borderRadius: 999,
    border: "none",
    background: "rgba(15,23,42,.58)",
    backdropFilter: "blur(6px)",
    color: "#fff",
    fontSize: 11.5,
    fontWeight: 700,
    lineHeight: 1,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  coverLeftControls: {
    position: "absolute",
    zIndex: 3,
    top: 10,
    left: 10,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  coverBackButton: {
    position: "relative",
    width: 32,
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,.35)",
    background: "rgba(15,23,42,.58)",
    backdropFilter: "blur(6px)",
    color: "#fff",
    fontSize: 13,
    cursor: "pointer",
  },
  coverPasswordButton: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 30,
    padding: "6px 11px 6px 10px",
    borderRadius: 999,
    border: "none",
    background: "rgba(15,23,42,.58)",
    backdropFilter: "blur(6px)",
    color: "#fff",
    fontSize: 11.5,
    fontWeight: 700,
    lineHeight: 1,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  avatar: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  avatarFallback: {
    fontSize: 38,
    fontWeight: 600,
    color: COLORS.primary,
  },
  name: {
    margin: "10px 0 2px",
    color: COLORS.text,
    fontSize: 20.5,
    lineHeight: 1.12,
    fontWeight: 700,
    letterSpacing: "-.032em",
    overflowWrap: "anywhere",
  },
  jobTitle: {
    margin: 0,
    color: COLORS.text,
    fontSize: 13.5,
    lineHeight: 1.35,
    fontWeight: 600,
    overflowWrap: "anywhere",
  },
  companyName: {
    margin: "2px 0 0",
    color: COLORS.textSecondary,
    fontSize: 12.5,
    lineHeight: 1.35,
    fontWeight: 400,
    overflowWrap: "anywhere",
  },
  description: {
    margin: "7px 0 0",
    color: "#475467",
    fontSize: 12.5,
    lineHeight: 1.45,
    maxWidth: 380,
    overflowWrap: "anywhere",
  },
  content: {
    padding: "8px 16px 24px",
  },
  section: {
    marginTop: 16,
  },
  sectionTitle: {
    margin: "0 0 8px",
    color: COLORS.text,
    fontSize: 14.5,
    lineHeight: 1.25,
    fontWeight: 700,
    letterSpacing: "-.02em",
  },
  contactGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  contactTile: {
    width: 62,
    height: 62,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    border: "1px solid rgba(15,23,42,.06)",
    background: "linear-gradient(145deg, #ffffff 0%, #f4f6f9 100%)",
    color: COLORS.primary,
    textDecoration: "none",
    boxShadow: "var(--shadow-sm)",
  },
  contactTileIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 25,
    lineHeight: 1,
  },
  linkList: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 8,
  },
  linkCard: {
    minHeight: 58,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 15,
    border: "1px solid rgba(15,23,42,.06)",
    background: "linear-gradient(145deg, #ffffff 0%, #f5f7fa 100%)",
    color: COLORS.text,
    textDecoration: "none",
    boxShadow: "var(--shadow-sm)",
  },
  linkCardIcon: {
    width: 38,
    height: 38,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    background: "#fff",
    flexShrink: 0,
    boxShadow: SHADOWS.sm,
    border: "1px solid rgba(15,23,42,.05)",
  },
  linkCardLabel: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontWeight: 650,
    lineHeight: 1.3,
    textAlign: "left",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: COLORS.textSecondary,
  },
  linkCardArrow: {
    flexShrink: 0,
    color: "#98a2b3",
    fontSize: 13,
  },
  linkIconImage: {
    width: 28,
    height: 28,
    objectFit: "contain",
  },
  linkIconFallback: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
  },
  socialGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  iconTile: {
    width: 62,
    height: 62,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    border: "1px solid rgba(15,23,42,.06)",
    background: "linear-gradient(145deg, #ffffff 0%, #f4f6f9 100%)",
    textDecoration: "none",
    boxShadow: "var(--shadow-sm)",
  },
  groupTrigger: {
    padding: 0,
    font: "inherit",
    cursor: "pointer",
    appearance: "none",
  },
  groupModalMask: {
    background: "rgba(15,23,42,.48)",
    backdropFilter: "blur(5px)",
  },
  groupModalContent: {
    padding: 0,
    borderRadius: 28,
    overflow: "hidden",
    boxShadow: "0 28px 80px rgba(15,23,42,.24)",
  },
  groupModalBody: {
    padding: "34px 22px 24px",
  },
  groupModalIconWrap: {
    width: 82,
    height: 82,
    margin: "0 auto 22px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    background: "linear-gradient(145deg, #fff 0%, #eef3fa 100%)",
    boxShadow: "0 12px 28px rgba(15,23,42,.12)",
  },
  groupModalIcon: {
    width: 52,
    height: 52,
    objectFit: "contain",
  },
  groupModalIconFallback: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 44,
    lineHeight: 1,
  },
  groupModalList: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 12,
  },
  groupModalRow: {
    minHeight: 62,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: "4px 8px",
    padding: "14px 18px",
    border: "1px solid rgba(15,23,42,.035)",
    borderRadius: 18,
    background: "#f4f5f7",
    color: COLORS.text,
    textAlign: "center",
    textDecoration: "none",
    boxShadow: "0 8px 20px rgba(15,23,42,.055)",
  },
  groupModalHeadline: {
    color: COLORS.textSecondary,
    fontSize: 14,
    lineHeight: 1.4,
    fontWeight: 500,
  },
  groupModalValue: {
    minWidth: 0,
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 1.4,
    fontWeight: 500,
    overflowWrap: "anywhere",
  },
  publicFooter: {
    width: "100%",
    minHeight: 48,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "10px 17px",
    background: "#fff",
    color: COLORS.textSecondary,
    fontSize: 12.5,
    fontWeight: 500,
    borderTop: "1px solid rgba(15,23,42,.06)",
    boxShadow: "none",
    marginTop: "auto",
  },
} satisfies Record<string, CSSProperties>;
