import type { CSSProperties } from "react";
import { COLORS } from "../../constants/ui";

export const companyLogoCoverMediaStyle = {
  boxSizing: "border-box",
  padding: "48px 8% 56px",
  background: "transparent",
} satisfies CSSProperties;

const coverMediaStyle = {
  position: "absolute",
  inset: 0,
  zIndex: 1,
  width: "100%",
  height: "100%",
  objectFit: "contain",
  objectPosition: "center",
  imageRendering: "auto",
} satisfies CSSProperties;

export const styles = {
  card: {
    background: "#fff",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    color: "var(--color-text)",
  },
  cover: {
    position: "relative",
    width: "100%",
    aspectRatio: "16 / 9",
    margin: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 0,
    boxShadow: "inset 0 0 0 1px rgba(15,23,42,.06)",
    isolation: "isolate",
  },
  coverMedia: coverMediaStyle,
  companyLogoCoverMedia: {
    ...coverMediaStyle,
    ...companyLogoCoverMediaStyle,
  },
  coverPattern: {
    position: "absolute",
    inset: 0,
    opacity: 0.18,
    backgroundImage:
      "radial-gradient(rgba(255,255,255,.8) 1px, transparent 1px)",
    backgroundSize: "18px 18px",
  },
  profileSection: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0 18px",
    textAlign: "center",
  },
  avatarWrap: {
    position: "relative",
    zIndex: 2,
    width: 110,
    height: 110,
    marginTop: -44,
  },
  avatarCircle: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    overflow: "hidden",
    border: "4px solid #fff",
    background: "#e9eef8",
    boxShadow:
      "0 12px 30px rgba(15,23,42,.16), 0 0 0 1px rgba(27,74,117,.10), 0 0 0 5px var(--color-primary-soft), 0 0 0 7px rgba(42,210,230,.08)",
  },
  shareButton: {
    position: "absolute",
    zIndex: 3,
    right: -10,
    bottom: 2,
    width: 34,
    height: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    background: "rgba(255,255,255,.92)",
    backdropFilter: "blur(12px) saturate(1.12)",
    border: "1px solid rgba(15,23,42,.1)",
    boxShadow: "0 10px 24px rgba(15,23,42,.13)",
    color: COLORS.text,
    fontSize: 14,
    cursor: "pointer",
  },
  coverEditButton: {
    position: "absolute",
    zIndex: 3,
    right: 14,
    top: 10,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 30,
    padding: "6px 11px 6px 10px",
    borderRadius: 999,
    border: "none",
    background: "rgba(15,23,42,.58)",
    backdropFilter: "blur(6px)",
    color: "#fff",
    fontSize: 11.5,
    fontWeight: 700,
    lineHeight: 1,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  coverLeftControls: {
    position: "absolute",
    zIndex: 3,
    top: 10,
    left: 10,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  coverBackButton: {
    position: "relative",
    width: 32,
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,.35)",
    background: "rgba(15,23,42,.58)",
    backdropFilter: "blur(6px)",
    color: "#fff",
    fontSize: 13,
    cursor: "pointer",
  },
  coverPasswordButton: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 30,
    padding: "6px 11px 6px 10px",
    borderRadius: 999,
    border: "none",
    background: "rgba(15,23,42,.58)",
    backdropFilter: "blur(6px)",
    color: "#fff",
    fontSize: 11.5,
    fontWeight: 700,
    lineHeight: 1,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  avatar: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  avatarFallback: {
    fontSize: 38,
    fontWeight: 600,
    color: COLORS.primary,
  },
  name: {
    margin: "10px 0 2px",
    color: COLORS.text,
    fontSize: 20.5,
    lineHeight: 1.12,
    fontWeight: 700,
    letterSpacing: "-.032em",
    overflowWrap: "anywhere",
  },
  roleAndCompany: {
    margin: "2px 0 0",
    color: COLORS.textSecondary,
    fontSize: 13.5,
    lineHeight: 1.4,
    fontWeight: 400,
    overflowWrap: "anywhere",
  },
  content: {
    padding: "8px 16px 24px",
  },
  section: {
    marginTop: 16,
  },
  aboutCard: {
    marginTop: 16,
    padding: "14px 16px",
    border: "1px solid rgba(15,23,42,.07)",
    borderRadius: 18,
    background: "#fff",
    boxShadow: "var(--shadow-sm)",
    textAlign: "left",
  },
  aboutTitle: {
    margin: "0 0 6px",
    color: COLORS.text,
    fontSize: 14,
    lineHeight: 1.3,
    fontWeight: 700,
  },
  aboutText: {
    margin: 0,
    color: COLORS.textSecondary,
    fontSize: 13.5,
    lineHeight: 1.55,
    overflowWrap: "anywhere",
    whiteSpace: "pre-wrap",
  },
  sectionTitle: {
    margin: "0 0 8px",
    color: COLORS.text,
    fontSize: 14.5,
    lineHeight: 1.25,
    fontWeight: 700,
    letterSpacing: "-.02em",
  },
  contactGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  linkList: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 8,
  },
  socialGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
} satisfies Record<string, CSSProperties>;

export function getCoverStyle(
  image?: string,
  isCompanyLogo = false,
): CSSProperties {
  return {
    ...styles.cover,
    background: isCompanyLogo
      ? "transparent"
      : image
        ? "linear-gradient(145deg, #eef3f9 0%, #ffffff 48%, #e9eff7 100%)"
        : "linear-gradient(145deg, var(--card-accent-deep, #0d2466) 0%, var(--card-accent, #1657c9) 58%, #2a8fde 100%)",
  };
}
